if [ -z $DATABASE_HOST ]; then
	export DATABASE_HOST="localhost" 
fi

if [ -z $DATABASE_PORT ]; then
	export DATABASE_PORT=3306 
fi

if [ -z $DATABASE_NAME ]; then
	export DATABASE_NAME="mydatabase" 
fi

if [ -z $MYSQL_USER ]; then
	export MYSQL_USER="usuario" 
fi

if [ -z $MYSQL_PASSWORD ]; then
	export MYSQL_PASSWORD="senha" 
fi

if [ -z $REDIS_HOST ]; then
	export REDIS_HOST="localhost" 
fi

if [ -z $REDIS_PORT ]; then
	export REDIS_PORT=6379
fi

if [ -z $SPRINGDATAAPI_SERVER_PORT ]; then
	export SPRINGDATAAPI_SERVER_PORT=8443
fi

if [ -z $SPRINGDATAAPI_SERVER_COMPRESSION_ENABLED ]; then
	export SPRINGDATAAPI_SERVER_COMPRESSION_ENABLED=true
fi

if [ -z $SPRINGDATAAPI_SERVER_COMPRESSION_MIN_RESPONSE_SIZE ]; then
	export SPRINGDATAAPI_SERVER_COMPRESSION_MIN_RESPONSE_SIZE="2MB"
fi

if [ -z $SPRINGDATAAPI_TOMCAT_ACCEPT_COUNT ]; then
	export SPRINGDATAAPI_TOMCAT_ACCEPT_COUNT=200
fi

if [ -z $SPRINGDATAAPI_TOMCAT_MAX_CONNECTIONS ]; then
	export SPRINGDATAAPI_TOMCAT_MAX_CONNECTIONS=20000
fi

if [ -z $SPRINGDATAAPI_TOMCAT_MAX_THREADS ]; then
	export SPRINGDATAAPI_TOMCAT_MAX_THREADS=200
fi

if [ -z $SPRINGDATAAPI_TOMCAT_MIN_SPARE_THREADS ]; then
	export SPRINGDATAAPI_TOMCAT_MIN_SPARE_THREADS=10
fi

if [ -z $SPRINGDATAAPI_TOMCAT_MAX_HTTP_POST_SIZE ]; then
	export SPRINGDATAAPI_TOMCAT_MAX_HTTP_POST_SIZE="2MB"
fi

if [ -z $SPRINGDATAAPI_TOMCAT_MAX_SWALLOW_SIZE ]; then
	export SPRINGDATAAPI_TOMCAT_MAX_SWALLOW_SIZE="2MB"
fi









