# Variaveis de ambiente do app spring-data-api

export DATABASE_HOST="localhost"
export DATABASE_PORT="3306"
export DATABASE_NAME="mydatabase"
export MYSQL_USER="usuario"
export MYSQL_PASSWORD="senha"
export REDIS_HOST="localhost"
export REDIS_PORT="6379"
export TOMCAT_PORT="8443"
export TOMCAT_COMPRESSION_ENABLED="true"
export TOMCAT_COMPRESSION_MIN_RESPONSE_SIZE="2MB"
export TOMCAT_ACCEPT_COUNT="400"
export TOMCAT_MAX_CONNECTIONS="20000"
export TOMCAT_MAX_THREADS="800"
export TOMCAT_MIN_SPARE_THREADS="400"
export TOMCAT_MAX_HTTP_POST_SIZE="2MB"
export TOMCAT_MAX_SWALLOW_SIZE="2MB"
